"""posts table message seen column added

Revision ID: e59ad53dd686
Revises: 60a094282eea
Create Date: 2020-06-15 09:46:59.972834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59ad53dd686'
down_revision = '60a094282eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'seen')
    # ### end Alembic commands ###
